// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilmbqmlkvcvuxmmcuadc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsbWJxbWxrdmN2dXhtbWN1YWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTc5NzksImV4cCI6MjA2MDI3Mzk3OX0.wzbfayR8hmaSiVLNOYWI8_5k29KIxUOrhXh8B0vvoy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);